use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let test_dir = Path::new(&manifest_dir).join("test_programs");

    let ignored = read_ignored(&test_dir);
    let mut entries = Vec::new();
    for entry in fs::read_dir(&test_dir).expect("read test_programs") {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        if path.extension().is_some_and(|ext| ext == "prim") {
            let mut expected = path.clone();
            expected.set_extension("expected");
            if !expected.exists() {
                panic!("Missing .expected file for {}", path.display());
            }
            entries.push((path, expected));
        }
    }

    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs\n");

    for (prim, expected) in entries {
        let stem_str = prim.file_stem().unwrap().to_string_lossy().to_string();
        let ignore_attr = if ignored.iter().any(|s| s == &stem_str) {
            "#[ignore]\n"
        } else {
            ""
        };
        generated.push_str(&format!(
            "{}#[test]\nfn case_{}() {{\n    run_test_program(std::path::Path::new({:?}), std::path::Path::new({:?}));\n}}\n\n",
            ignore_attr,
            stem_str.replace(|c: char| !c.is_alphanumeric(), "_"),
            prim.to_string_lossy(),
            expected.to_string_lossy()
        ));
    }

    let out_path = PathBuf::from(out_dir).join("test_programs_cases.rs");
    let mut file = fs::File::create(out_path).expect("create generated tests");
    file.write_all(generated.as_bytes())
        .expect("write generated tests");
}

fn read_ignored(test_dir: &Path) -> Vec<String> {
    let ignored_file = test_dir.join("ignored.txt");
    if !ignored_file.exists() {
        return Vec::new();
    }
    let contents = fs::read_to_string(&ignored_file).expect("read ignored.txt");
    contents
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty())
        .map(|s| s.to_string())
        .collect()
}
